using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DashBoard
{
    /// <summary>
    /// 
    /// </summary>
    class Archive
    {

        /// <summary>
        /// 
        /// </summary>
        public void DeleteDuplicates()
        {
            deleteDuplicateError();
            deleteDuplicateUserError();

        }

        /// <summary>
        /// Errors that occur that are duplicates within a very close timeframe.
        /// </summary>
        public void DeleteRepeatedError()
        {
            archiveError();
        }



        /// <summary>
        /// Errors that are the same made from different User/User-Agent 
        /// </summary>
        /// <example>
        /// User A, User B, and GoogleBot visits SomePage.cshtml and it generates the exact same error for all Visits that were made.
        /// </example>
        public void deleteDuplicateError()
        {
            archiveError();
        }


        /// <summary>
        /// Errors that are the same and made by the same User/User-Agent
        /// </summary>
        /// <example>
        /// A user keeps visiting the same page or hitting reload generating the same error for the same user repeately.
        /// This can be in multiple session or different visits. 
        /// </example>
        public void deleteDuplicateUserError()
        {
            archiveUser();
        }



        //ToDo: Define "Exact" same Error

        /// <summary>
        /// Takes a duplicate error and record the differences between the error and gets rid of the duplicate information. 
        /// </summary>
        /// <example>
        /// Multiple Users visit Page-2.cshtml it generates the "exact" same error.
        /// Unique information that is recorded would be the Number of times the error happen, and the date time of those errors.
        /// </example>
        /// <returns>
        /// 1. New xml file with the File name of the GuidID ("errorId") of the Error to be Archived saved in the /Archive folder.
        /// 2. Updates an already existing Error with updated information on the new instances of the same error 
        ///    (Update Error Count, adds another Date-Time to the file <datetime>DateTime new error</datetime>).
        /// </returns>
        public void archiveError()
        {

        }

        /// <summary>
        /// Takes duplicate information on a User away and only record unique information about a user. 
        /// </summary>
        /// <example>
        /// User A Vists Page-1.cshtml 5 times and each time generates the "exact" same error.  
        /// Unique information on user would be User-Agent,Cookie, Number of times same error was generated by user, date time of errors, 
        /// and the ErrorID of the (first | latest)? error. 
        /// </example>
        public void archiveUser()
        {

        }







    }
}
